In [130]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [131]:
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
import pandas as pd
import numpy as np
df = pd.read_csv("gdrive/My Drive/Colab Notebooks/CS445/penguins.txt",delimiter = "\t")

In [132]:
#independent features
X = df[['bill_length_mm','flipper_length_mm']]
#Dependent features
y = df['species']

In [133]:
#Data traning
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [134]:
#Linear Discriminant Analysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clf = LinearDiscriminantAnalysis()
clf.fit(X_train, y_train)

LinearDiscriminantAnalysis()

In [135]:
y_pred = clf.predict(X_test)

In [136]:
y_pred

array(['Adelie', 'Chinstrap', 'Gentoo', 'Gentoo', 'Adelie', 'Gentoo',
       'Adelie', 'Gentoo', 'Gentoo', 'Gentoo', 'Gentoo', 'Adelie',
       'Adelie', 'Gentoo', 'Gentoo', 'Gentoo', 'Gentoo', 'Gentoo',
       'Adelie', 'Adelie', 'Gentoo', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Chinstrap', 'Adelie', 'Chinstrap', 'Gentoo',
       'Gentoo', 'Adelie', 'Gentoo', 'Chinstrap', 'Chinstrap', 'Adelie',
       'Adelie', 'Gentoo', 'Adelie', 'Gentoo', 'Adelie', 'Chinstrap',
       'Gentoo', 'Gentoo', 'Chinstrap', 'Gentoo', 'Adelie', 'Adelie',
       'Adelie', 'Chinstrap', 'Adelie', 'Adelie', 'Adelie', 'Gentoo',
       'Chinstrap', 'Gentoo', 'Chinstrap', 'Adelie', 'Adelie',
       'Chinstrap', 'Gentoo', 'Gentoo', 'Gentoo', 'Adelie', 'Adelie',
       'Adelie', 'Gentoo'], dtype='<U9')

In [137]:
#Confusion Matrix for LDA
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
acc = accuracy_score(y_test,y_pred)
print('Confusion Matrix for LDA')
print(cm)
print(acc)

Confusion Matrix for LDA
[[26  1  1]
 [ 3 10  0]
 [ 0  0 26]]
0.9253731343283582


In [138]:
#Quadratic Discrimant Analaysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
clf = QuadraticDiscriminantAnalysis()
clf.fit(X_train, y_train)

QuadraticDiscriminantAnalysis()

In [139]:
qda_pred = clf.predict(X_test)

In [140]:
qda_pred

array(['Adelie', 'Chinstrap', 'Gentoo', 'Gentoo', 'Adelie', 'Gentoo',
       'Adelie', 'Gentoo', 'Gentoo', 'Gentoo', 'Gentoo', 'Adelie',
       'Adelie', 'Gentoo', 'Gentoo', 'Gentoo', 'Gentoo', 'Gentoo',
       'Adelie', 'Adelie', 'Gentoo', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Chinstrap', 'Adelie', 'Chinstrap', 'Gentoo',
       'Gentoo', 'Adelie', 'Gentoo', 'Chinstrap', 'Chinstrap', 'Adelie',
       'Adelie', 'Gentoo', 'Adelie', 'Gentoo', 'Adelie', 'Chinstrap',
       'Gentoo', 'Gentoo', 'Chinstrap', 'Gentoo', 'Adelie', 'Adelie',
       'Adelie', 'Chinstrap', 'Adelie', 'Adelie', 'Adelie', 'Gentoo',
       'Chinstrap', 'Gentoo', 'Chinstrap', 'Gentoo', 'Adelie',
       'Chinstrap', 'Gentoo', 'Gentoo', 'Gentoo', 'Adelie', 'Adelie',
       'Adelie', 'Gentoo'], dtype=object)

In [141]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,qda_pred)
acc = accuracy_score(y_test,qda_pred)
print('Confusion Matrix for QDA:')
print(cm)
print(acc)

Confusion Matrix for QDA:
[[25  1  2]
 [ 3 10  0]
 [ 0  0 26]]
0.9104477611940298


In [142]:
#LDA Covariance Matrix
lda = LinearDiscriminantAnalysis(store_covariance=True).fit(X_train,y_train)
print('Linear:')
print(lda.covariance_)

Linear:
[[ 8.41554747  8.13109425]
 [ 8.13109425 42.44541734]]


In [143]:
#QDA Covarience Matrix
qda = QuadraticDiscriminantAnalysis(store_covariance=True).fit(X_train,y_train)
print('Quadratic:')
print(qda.covariance_)


Quadratic:
[array([[ 6.92111546,  4.3418224 ],
       [ 4.3418224 , 39.72157033]]), array([[10.09355556,  8.37185185],
       [ 8.37185185, 47.88417508]]), array([[ 9.60557737, 13.07388967],
       [13.07388967, 44.10121552]])]
